---
title: "Sars_initial_check"
author: "Chris LeBoa"
date: "5/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("RCurl")
library(tidyverse)
library(RCurl)
data <- read_csv("/Users/ChrisLeBoa/Downloads/SARSCoV2Transmission_DATA_2020-05-22_1254.csv")

glimpse(data)
```

#API Export 
```{r}

travel_phone <- postForm(
    uri='https://redcap.stanford.edu/api/',
    token='0AF77C06732E8B075AB460C3C45F8C73',
    content='report',
    format='csv',
    report_id='69901',
    csvDelimiter='',
    rawOrLabel='raw',
    rawOrLabelHeaders='raw',
    exportCheckboxLabel='false',
    returnFormat='csv'
)

travel_eform <- postForm(
    uri='https://redcap.stanford.edu/api/',
    token='0AF77C06732E8B075AB460C3C45F8C73',
    content='report',
    format='csv',
    report_id='69902',
    csvDelimiter='',
    rawOrLabel='raw',
    rawOrLabelHeaders='raw',
    exportCheckboxLabel='false',
    returnFormat='csv'
)


```

#Read in data as tables 
```{r}
data_phone <- 
  read_csv(travel_phone) %>%
    filter(is.na(redcap_repeat_instrument)) %>% 
  rename_all(~str_remove(., "_e"))


data_eform <- 
  read_csv(travel_eform) %>%
    filter(is.na(redcap_repeat_instrument)) %>% 
  rename_all(~str_remove(., "_e"))
```

```{r}
data %>% 
  filter(!is.na(hospital_name_e )) %>% 
  select(hospital_name_e, hospital_loc_e)

data %>% 
  filter(!is.na(n_trips_e)) %>% 
  select(n_trips_e, trip1_location_e)

data %>% 
  filter(str_detect(study_interest_e, "yes|Yes")) %>% 
  select(study_interest_e , email) %>% 
  write_csv("/Users/ChrisLeBoa/Downloads/emails.csv")
```

